# Generated by Django 2.1.1 on 2019-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_remove_userprofileinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
