# Generated by Django 2.1.1 on 2019-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_userprofileinfo_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('city_state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
