# Generated by Django 2.2.1 on 2019-05-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0006_tutorquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
