# Generated by Django 2.2.1 on 2019-05-30 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0007_delete_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutionPointRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('Subjects_you_wish_to_teach', models.CharField(blank=True, max_length=200, null=True)),
                ('What_is_the_minimum_tenure_you_wish_to_be_with_us', models.CharField(blank=True, max_length=200, null=True)),
                ('What_languages_your_teachers_know', models.CharField(blank=True, max_length=200, null=True)),
                ('Give_us_a_short_description_about_your_institute', models.TextField(blank=True, max_length=500, null=True)),
                ('Level_of_targeted_students', models.CharField(blank=True, max_length=200, null=True)),
                ('Your_Specialities', models.CharField(blank=True, max_length=200, null=True)),
                ('How_old_is_your_institute', models.CharField(blank=True, max_length=200, null=True)),
                ('Fee_for_courses', models.CharField(blank=True, max_length=200, null=True)),
                ('what_are_your_expectations_from_findatution', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
