# Generated by Django 2.2.1 on 2019-05-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0008_tutionpointregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutionpointregister',
            old_name='What_is_the_minimum_tenure_you_wish_to_be_with_us',
            new_name='What_is_the_minimum_time_you_wish_to_be_with_us',
        ),
    ]
