# Generated by Django 2.2.1 on 2019-05-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_auto_20190531_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutionpointregister',
            old_name='Level_of_targeted_students',
            new_name='Level_of_target_students',
        ),
    ]
