# Generated by Django 2.2.1 on 2019-06-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0010_auto_20190531_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutionpointregister',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='tutorquestion',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
