# Generated by Django 2.1.1 on 2019-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0012_auto_20190612_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutionpointregister',
            name='what_are_your_expectations_from_findatution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tutorquestion',
            name='what_are_your_expectations_from_findatution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='what_do_you_expect_from_our_tutor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
