# Generated by Django 2.2.1 on 2019-06-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0013_auto_20190612_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorquestion',
            name='Highest_degree',
            field=models.ImageField(blank=True, upload_to='Highest_degree'),
        ),
    ]
