# Generated by Django 2.1.1 on 2019-06-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0014_tutorquestion_highest_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
