# Generated by Django 2.1.1 on 2019-06-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0015_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
