# Generated by Django 2.1.1 on 2019-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0016_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorquestion',
            name='Highest_degree',
            field=models.FileField(blank=True, upload_to='Highest_degree'),
        ),
    ]
