# Generated by Django 2.2.1 on 2019-06-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0017_auto_20190619_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorquestion',
            name='Highest_degree',
        ),
    ]
