# Generated by Django 2.2.1 on 2019-06-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0018_remove_tutorquestion_highest_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorquestion',
            name='Highest_degree',
            field=models.FileField(blank=True, upload_to='Highest_degree'),
        ),
    ]
