# Generated by Django 2.2.1 on 2019-06-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0019_tutorquestion_highest_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorquestion',
            name='Your_Specialities',
        ),
        migrations.AddField(
            model_name='tutionpointregister',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorquestion',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
