# Generated by Django 2.2.1 on 2019-06-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0020_auto_20190627_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorquestion',
            name='Upload_certificate',
            field=models.FileField(blank=True, upload_to='Upload_certificate'),
        ),
        migrations.AlterField(
            model_name='tutorquestion',
            name='Highest_degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
