# Generated by Django 2.2.3 on 2019-07-28 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0022_auto_20190629_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('Your_Board', models.CharField(blank=True, max_length=200, null=True)),
                ('Your_class', models.CharField(blank=True, max_length=200, null=True)),
                ('Language_You_Speak', models.CharField(blank=True, max_length=200, null=True)),
                ('Subject_You_want_to_study', models.CharField(blank=True, max_length=200, null=True)),
                ('Preferred_time', models.CharField(blank=True, max_length=200, null=True)),
                ('Stream', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DanceStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('Danceform_You_want_to_learn', models.CharField(blank=True, max_length=200, null=True)),
                ('Preferred_time', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('What_would_you_like_to_learn', models.CharField(blank=True, max_length=200, null=True)),
                ('Preferred_time', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YogaStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('What_Yoga_form_want_to_learn', models.CharField(blank=True, max_length=200, null=True)),
                ('Preferred_time', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='tutorquestion',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='TutionPointRegister',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
